# Portable bash environment.

export TERM=xterm-256color

# If not running interactively, don't do anything
case $- in
    *i*) ;;
      *) return;;
esac

env_etc_dir=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd -P)
export ENV_HOME=$(cd -- "$env_etc_dir/.." && pwd -P)
unset env_etc_dir

################################################################################
# Options
################################################################################
# don't put duplicate lines or lines starting with space in the history.
# See bash(1) for more options
HISTCONTROL=ignoreboth

# append to the history file, don't overwrite it
shopt -s histappend

# for setting history length see HISTSIZE and HISTFILESIZE in bash(1)
HISTSIZE=1000
HISTFILESIZE=2000

################################################################################
# Aliases
################################################################################
# ls
function lsd() {
    command "$ENV_HOME/bin/lsd" --config-file "$XDG_CONFIG_HOME/lsd/config.yaml" "$@"
}
alias l='lsd -l'
alias la='lsd -lA'
alias lf='lsd -l --group-directories-first'
alias ll='lsd -lAL'
alias ls='lsd'
alias lt='lsd --tree'
alias lta='lsd --tree -a'
alias ltt='lsd --tree --depth'

# git
git_log_format="%C(auto)%h%d %s %C(black)%C(bold)%cr%Creset %Cblue[%an]" # relative commit data & author name
alias gb='git branch'
alias gc='git commit'
alias gca='git commit --amend'
alias gcm='git commit -m'
alias gcs='git commit -s'
alias gch='git cherry-pick'
alias gl='git log'
alias gls="git log --pretty=format:'$git_log_format'"
alias gla="git log --pretty=format:'$git_log_format' --all --graph"
alias gll="git log --pretty=format:'$git_log_format' --numstat"
alias glf='git log --pretty=fuller'
alias gp='git pull'
alias GP='git push'
alias gpra='git pull --rebase --autostash'
alias gr='git remote'
alias gsh='git stash'
alias gst='git status'
alias gsw='git switch'
alias gwt='git worktree'

################################################################################
# Functions
################################################################################
function bell() {
  printf '\a'
}

function bell_checked() {
  if [[ -n "$NOTIFY_BELL" ]]; then
    bell
  fi
}

################################################################################
# Environment
################################################################################
# XDG Paths
export XDG_CONFIG_HOME="$ENV_HOME/config"
export XDG_CACHE_HOME="$ENV_HOME/cache"
export XDG_DATA_HOME="$ENV_HOME/share"
export XDG_STATE_HOME="$ENV_HOME/state"

export STARSHIP_CONFIG="$ENV_HOME/config/starship.toml"

# editor
export EDITOR=nvim
export VISUAL="nvim"

export PATH="$ENV_HOME/bin:$HOME/.local/bin:$PATH"

# ensure compile_commands.json is always generated
export CMAKE_EXPORT_COMPILE_COMMANDS=1

# ensure truecolor over SSH
export COLORTERM=truecolor

################################################################################
# Other tools
################################################################################
eval "$(fzf --bash)"

# vivid to generate colorized output
export LS_COLORS="$(vivid generate catppuccin-mocha)"

eval "$(zoxide init --hook prompt bash)"
eval "$(starship init bash)"
PROMPT_COMMAND="bell_checked; $PROMPT_COMMAND"
