# ── Settings ──────────────────────────────────────────────────────────────────
set -g mouse on
set -g base-index 1
set -s escape-time 50
set -g focus-events on
set -g renumber-windows on
set -g default-terminal "tmux-256color"
set -ga terminal-overrides ",xterm-256color:Tc"

# ── Keybinds ──────────────────────────────────────────────────────────────────
# split panes using "\" and "-", keep current path
bind '\' split-window -h -c "#{pane_current_path}"
bind -  split-window -v -c "#{pane_current_path}"
unbind '"'
unbind %

# copy mode — vim keys + mouse
bind -T copy-mode-vi v                 send -X begin-selection
bind -T copy-mode-vi y                 send -X copy-selection
bind -T copy-mode-vi MouseDragEnd1Pane send -X copy-selection

# fix Home / End keys in many terminals
bind -n Home send Escape "[H"
bind -n End  send Escape "[F"

# reload config
bind r run-shell 'tmux source "$ENV_HOME/config/tmux/tmux.conf"' \; display "config reloaded"

# send command to all panes in session
bind e command-prompt -p "Command:" \
         "run \"tmux list-panes -s -F '##{session_name}:##{window_index}.##{pane_index}' \
        | xargs -I PANE tmux send-keys -t PANE '%1' Enter\""

# jump to last shell prompt
bind b copy-mode\; send-keys -X start-of-line\; send-keys -X search-backward "[]"

# send Ctrl-j (newline in some CLIs)
bind C-j send-keys C-j
